dryrun=false
cron=true
timezone="Asia/Shanghai"
createcron="45 22 * * *"
deletecron="0 2 * * *"
[[database]]
name="TestDB"
username="root"
password="password"
server="127.0.0.1"
port=3306
database="test"
mode="to_days"
partkey="hiredate"
table="range_datetime"
createdays=7
purgedays=7
